# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 513ba78bed31f25e66fcffeaf8ea21fb355d4579c0507a1131f26cdcfe93a05ea8ac994f65eb742f4c9ba4f6ace4d82a80e468e150413691c8eb8c4a794a6e8f

test:
  secret_key_base: cdeff7054060955e96ed9f35fca426cbb1abbfaa6e2358227bc91bfe83f95bb4d530660f628c3da9b99a00817d25c34990dba99c1decd1a64c1e97d08502ebf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
